travis: wild guess

diff --git a/test/checker/run-python-bindings.in b/test/checker/run-python-bindings.in
--- a/test/checker/run-python-bindings.in
+++ b/test/checker/run-python-bindings.in
@@ -10,10 +10,20 @@ export base=$PWD/python-build
 (
     cd ../../python
     echo "@PYTHON@" setup.py install -f --install-base="$base" --install-purelib="$base" --install-platlib="$base" --install-scripts="$base" --install-data="$base" --install-headers="$base"
-    "@PYTHON@" setup.py install -f --install-base="$base" --install-purelib="$base" --install-platlib="$base" --install-scripts="$base" --install-data="$base" --install-headers="$base"
+    if ! "@PYTHON@" setup.py install -f --install-base="$base" --install-purelib="$base" --install-platlib="$base" --install-scripts="$base" --install-data="$base" --install-headers="$base"; then
+        echo "Failed to install python libs to $base, trying anyway with guessed PYTHONPATH ..."
+    fi
 )
-
 export PYTHONPATH="$base:$PYTHONPATH"
+
+if [[ "$(uname)" = Darwin ]]; then
+    v=$(sw_vers -productVersion)
+    os_vers=( ${v//./ } )
+    os_vers_major="${os_vers[0]}"
+    os_vers_minor="${os_vers[1]}"
+    PYTHONPATH="../../python/build/lib.macosx-${os_vers_major}.${os_vers_minor}-x86_64-3.6:$PYTHONPATH"
+fi
+
 export LD_LIBRARY_PATH="../../src/.libs:$LD_LIBRARY_PATH"
 
 "@PYTHON@" test-python-bindings.py
